### ISSUE TITLE
unit test is failing

### ISSUE THREAD

**Issue by stevez** [jihchi/vitejs-template-react-rescript#10] opened 2022-10-24 03:24 UTC
npm version: 14.16.1
working on latest head.

result:
FAIL  tests/App_test.bs.js [ tests/App_test.bs.js ]
Error: No test suite found in file .../tests/App_test.bs.js

can you help us fix it?

**Comment by jihchi** [comment] 2022-12-11 04:49
Would you please try latest commit?

[Latest commit](640458864aa920f2866e24ae0cb29e9c03b1074f) (Vite 4 is supported) works on my machine:

```sh
$ npm test

> vite-react-rescript-starter@1.0.0 test
> vitest

[@jihchi/vite-plugin-rescript] Dependency on @rescript/react
[@jihchi/vite-plugin-rescript] Dependency on @ryyppy/rescript-promise
[@jihchi/vite-plugin-rescript] Dependency on rescript-webapi
[@jihchi/vite-plugin-rescript] Dependency on rescript-vitest
[@jihchi/vite-plugin-rescript] Dependency Finished
[@jihchi/vite-plugin-rescript] >>>> Start compiling
[@jihchi/vite-plugin-rescript] >>>> Finish compiling

 DEV  v0.25.6 /home/jihchi/code/vitejs-template-react-rescript

 ✓ tests/App_test.bs.js (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  05:48:12
   Duration  1.97s (transform 626ms, setup 146ms, collect 178ms, tests 51ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit

$ npm version
{
  'vite-react-rescript-starter': '1.0.0',
  npm: '8.19.2',
  node: '18.12.1',
  v8: '10.2.154.15-node.12',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '3.0.7+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

**Comment by krokofant** [comment] 2023-05-09 22:25
Just did this and testing fails:
```
npx degit jihchi/vitejs-template-react-rescript my-vitejs-react-rescript
cd my-vitejs-react-rescript
npx vite
npx vitest
```
![image](https://github.com/jihchi/vitejs-template-react-rescript/assets/5908498/9da43996-8933-4de4-a09f-ed6254fa3013)

Tried it with git clone (commit 01f1ca66126487de98ceaf191c706ea08cc5e7d0)
```
git clone https://github.com/jihchi/vitejs-template-react-rescript.git
cd .\vitejs-template-react-rescript\
npm ci
npm run test
```
![image](https://github.com/jihchi/vitejs-template-react-rescript/assets/5908498/377fd439-1452-4395-a8c5-e963c666d06e)

```
❯ npm version
{
  'vite-react-rescript-starter': '1.0.0',
  npm: '9.5.1',
  node: '18.16.0',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.0',
  brotli: '1.0.9',
  cldr: '42.0',
  icu: '72.1',
  llhttp: '6.0.10',
  modules: '108',
  napi: '8',
  nghttp2: '1.52.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.8+quic',
  simdutf: '3.2.2',
  tz: '2022g',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13'
}
```
Tried on Windows 11.

**Comment by krokofant** [comment] 2023-05-10 11:13
Also tried it on macOS and the same nodejs version. Is this not reproducible by you @jihchi ? Are you installing the dependencies with npm ci?

I also tested on the exact same node version you're running and it still fails:
```powershell
docker run -it --rm --name my-running-script -v "${PWD}:/usr/src/app" -w /usr/src/app node:18.12.1-buster bash
npm ci
npm run test
```

**Comment by jihchi** [comment] 2023-05-11 16:16
Hi @krokofant , I've upgraded the rescript-vitest library and fixed broken test (for more details, click [here](https://github.com/jihchi/vitejs-template-react-rescript/compare/01f1ca66126487de98ceaf191c706ea08cc5e7d0...main)), it works for me.

Could you try to pull the latest commit (709c1724194fb5b3800466b527745c8a77592e74) and verify it?

**Comment by krokofant** [comment] 2023-05-11 23:20
@jihchi Yes, it works! 🥳

**Comment by krokofant** [comment] 2023-06-22 23:18
@jihchi Could you close this issue? 😊

**Closed as completed** 2023-06-23 05:58 UTC
